// @effect-diagnostics nodeBuiltinImport:off preferSchemaOverJson:off
import * as NodePath from "node:path";
import type { HomelabSkill } from "@t3tools/contracts";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";

/**
 * Fork-owned seam: materializes homelab skills into a runtime as real SKILL.md files.
 *
 * Two views are written:
 * - `<workspace>/.homelab/skills/<name>/SKILL.md` plus an index — the canonical, fully
 *   generated view every provider can read (and the one referenced by AGENTS.md).
 * - `<home>/.claude/skills/<name>/SKILL.md` and `<home>/.agents/skills/<name>/SKILL.md` —
 *   the user-level skill directories Claude Code and Codex/OpenCode discover, so skills
 *   auto-load for every provider without extra prompting.
 *
 * All subtrees are reconciled: stale generated skill dirs are pruned. Because
 * agents and host syncs may also write into the provider skill dirs, we only prune
 * entries this view previously managed — tracked in a `.homelab-managed.json`
 * manifest per directory — so a renamed/deleted skill stops auto-loading without
 * disturbing skills authored elsewhere.
 */

/** Home-relative skill directories providers auto-discover. */
export const HOMELAB_PROVIDER_SKILL_DIRS = [
  [".claude", "skills"],
  [".agents", "skills"],
] as const;

export interface HomelabSkillsViewInput {
  readonly workspaceRoot: string;
  readonly homeRoot: string;
  readonly skills: ReadonlyArray<HomelabSkill>;
}

function safeSkillSegment(name: string): string {
  const normalized = name.replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
  return normalized.length > 0 ? normalized.slice(0, 120) : "skill";
}

export function renderSkillMarkdown(skill: HomelabSkill): string {
  const body = skill.body.trimStart();
  if (body.startsWith("---")) {
    return skill.body;
  }
  return [
    "---",
    `name: ${skill.name}`,
    `description: ${skill.description.replace(/\n/g, " ")}`,
    "---",
    "",
    skill.body,
    "",
  ].join("\n");
}

function renderSkillsIndex(skills: ReadonlyArray<HomelabSkill>): string {
  return skills
    .map((skill) =>
      JSON.stringify({
        name: skill.name,
        scope: skill.scope,
        description: skill.description,
        path: `.homelab/skills/${safeSkillSegment(skill.name)}/SKILL.md`,
        updatedAt: skill.updatedAt,
      }),
    )
    .map((line) => `${line}\n`)
    .join("");
}

function renderSkillsReadme(): string {
  return [
    "# Homelab skills",
    "",
    "Reusable agent skills materialized from the homelab skill registry.",
    "Each `<name>/SKILL.md` describes when and how to apply one skill.",
    "",
    "- `index.jsonl` lists every skill visible to this runtime (global + this scope).",
    "- Author a new skill with `homelab skill add <name> --description ... --stdin`.",
    "- Promote one up the ladder with `homelab skill promote <name> --to project|global`.",
    "",
    "This directory is regenerated by the platform; do not edit files here directly.",
    "",
  ].join("\n");
}

export const writeHomelabSkillsView = Effect.fn("runtime.writeHomelabSkillsView")(function* (
  input: HomelabSkillsViewInput,
) {
  const fileSystem = yield* FileSystem.FileSystem;
  const skillsDir = NodePath.join(input.workspaceRoot, ".homelab", "skills");
  const providerSkillDirs = HOMELAB_PROVIDER_SKILL_DIRS.map((segments) =>
    NodePath.join(input.homeRoot, ...segments),
  );

  const expectedDirs = new Set(input.skills.map((skill) => safeSkillSegment(skill.name)));

  yield* fileSystem.makeDirectory(skillsDir, { recursive: true });
  yield* fileSystem.writeFileString(NodePath.join(skillsDir, "README.md"), renderSkillsReadme());
  yield* fileSystem.writeFileString(
    NodePath.join(skillsDir, "index.jsonl"),
    renderSkillsIndex(input.skills),
  );

  for (const skill of input.skills) {
    const segment = safeSkillSegment(skill.name);
    const markdown = renderSkillMarkdown(skill);
    const workspaceSkillDir = NodePath.join(skillsDir, segment);
    yield* fileSystem.makeDirectory(workspaceSkillDir, { recursive: true });
    yield* fileSystem.writeFileString(NodePath.join(workspaceSkillDir, "SKILL.md"), markdown);

    for (const providerSkillsDir of providerSkillDirs) {
      const providerSkillDir = NodePath.join(providerSkillsDir, segment);
      yield* fileSystem.makeDirectory(providerSkillDir, { recursive: true });
      yield* fileSystem.writeFileString(NodePath.join(providerSkillDir, "SKILL.md"), markdown);
    }
  }

  // Reconcile the fully generated workspace view: prune skill dirs that no longer exist.
  const entries = yield* fileSystem
    .readDirectory(skillsDir, { recursive: false })
    .pipe(Effect.orElseSucceed(() => [] as ReadonlyArray<string>));
  for (const entry of entries) {
    if (entry === "README.md" || entry === "index.jsonl") {
      continue;
    }
    if (!expectedDirs.has(entry)) {
      yield* fileSystem
        .remove(NodePath.join(skillsDir, entry), { recursive: true })
        .pipe(Effect.orElseSucceed(() => undefined));
    }
  }

  // Reconcile each provider skills dir. Prune only the segments this view managed
  // on a previous run (per that dir's manifest) and are now gone — never touch
  // skills authored by the agent or synced from the host. Without this, a
  // deleted/renamed skill kept auto-loading forever.
  for (const providerSkillsDir of providerSkillDirs) {
    const manifestPath = NodePath.join(providerSkillsDir, ".homelab-managed.json");
    const previouslyManaged = yield* fileSystem.readFileString(manifestPath).pipe(
      Effect.map((raw) => {
        const parsed: unknown = JSON.parse(raw);
        return Array.isArray(parsed)
          ? parsed.filter((entry): entry is string => typeof entry === "string")
          : [];
      }),
      Effect.orElseSucceed(() => [] as ReadonlyArray<string>),
    );
    for (const segment of previouslyManaged) {
      if (!expectedDirs.has(segment)) {
        yield* fileSystem
          .remove(NodePath.join(providerSkillsDir, segment), { recursive: true })
          .pipe(Effect.orElseSucceed(() => undefined));
      }
    }
    yield* fileSystem.makeDirectory(providerSkillsDir, { recursive: true }).pipe(Effect.ignore);
    yield* fileSystem
      .writeFileString(manifestPath, `${JSON.stringify([...expectedDirs].sort())}\n`)
      .pipe(Effect.orElseSucceed(() => undefined));
  }
});
