// @effect-diagnostics nodeBuiltinImport:off
import nodePath from "node:path";

import type { HomelabSkill } from "@t3tools/contracts";
import * as Effect from "effect/Effect";
import * as FileSystem from "effect/FileSystem";

/**
 * Fork-owned seam: materializes homelab skills into a runtime as real SKILL.md files.
 *
 * Two views are written:
 * - `<workspace>/.homelab/skills/<name>/SKILL.md` plus an index — the canonical, fully
 *   generated view every provider can read (and the one referenced by AGENTS.md).
 * - `<home>/.claude/skills/<name>/SKILL.md` — Claude Code's user-level skills directory,
 *   so skills are auto-discoverable there without extra prompting.
 *
 * The `.homelab/skills` subtree is reconciled (stale generated skill dirs are pruned);
 * `.claude/skills` is upsert-only because agents and host syncs may also write there.
 */

export interface HomelabSkillsViewInput {
  readonly workspaceRoot: string;
  readonly homeRoot: string;
  readonly skills: ReadonlyArray<HomelabSkill>;
}

function safeSkillSegment(name: string): string {
  const normalized = name.replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
  return normalized.length > 0 ? normalized.slice(0, 120) : "skill";
}

export function renderSkillMarkdown(skill: HomelabSkill): string {
  const body = skill.body.trimStart();
  if (body.startsWith("---")) {
    return skill.body;
  }
  return [
    "---",
    `name: ${skill.name}`,
    `description: ${skill.description.replace(/\n/g, " ")}`,
    "---",
    "",
    skill.body,
    "",
  ].join("\n");
}

function renderSkillsIndex(skills: ReadonlyArray<HomelabSkill>): string {
  return skills
    .map((skill) =>
      JSON.stringify({
        name: skill.name,
        scope: skill.scope,
        description: skill.description,
        path: `.homelab/skills/${safeSkillSegment(skill.name)}/SKILL.md`,
        updatedAt: skill.updatedAt,
      }),
    )
    .map((line) => `${line}\n`)
    .join("");
}

function renderSkillsReadme(): string {
  return [
    "# Homelab skills",
    "",
    "Reusable agent skills materialized from the homelab skill registry.",
    "Each `<name>/SKILL.md` describes when and how to apply one skill.",
    "",
    "- `index.jsonl` lists every skill visible to this runtime (global + this scope).",
    "- Author a new skill with `homelab skill add <name> --description ... --stdin`.",
    "- Promote one up the ladder with `homelab skill promote <name> --to project|global`.",
    "",
    "This directory is regenerated by the platform; do not edit files here directly.",
    "",
  ].join("\n");
}

export const writeHomelabSkillsView = Effect.fn("runtime.writeHomelabSkillsView")(function* (
  input: HomelabSkillsViewInput,
) {
  const fileSystem = yield* FileSystem.FileSystem;
  const skillsDir = nodePath.join(input.workspaceRoot, ".homelab", "skills");
  const claudeSkillsDir = nodePath.join(input.homeRoot, ".claude", "skills");

  const expectedDirs = new Set(input.skills.map((skill) => safeSkillSegment(skill.name)));

  yield* fileSystem.makeDirectory(skillsDir, { recursive: true });
  yield* fileSystem.writeFileString(nodePath.join(skillsDir, "README.md"), renderSkillsReadme());
  yield* fileSystem.writeFileString(
    nodePath.join(skillsDir, "index.jsonl"),
    renderSkillsIndex(input.skills),
  );

  for (const skill of input.skills) {
    const segment = safeSkillSegment(skill.name);
    const markdown = renderSkillMarkdown(skill);
    const workspaceSkillDir = nodePath.join(skillsDir, segment);
    yield* fileSystem.makeDirectory(workspaceSkillDir, { recursive: true });
    yield* fileSystem.writeFileString(nodePath.join(workspaceSkillDir, "SKILL.md"), markdown);

    const claudeSkillDir = nodePath.join(claudeSkillsDir, segment);
    yield* fileSystem.makeDirectory(claudeSkillDir, { recursive: true });
    yield* fileSystem.writeFileString(nodePath.join(claudeSkillDir, "SKILL.md"), markdown);
  }

  // Reconcile the fully generated workspace view: prune skill dirs that no longer exist.
  const entries = yield* fileSystem
    .readDirectory(skillsDir, { recursive: false })
    .pipe(Effect.orElseSucceed(() => [] as ReadonlyArray<string>));
  for (const entry of entries) {
    if (entry === "README.md" || entry === "index.jsonl") {
      continue;
    }
    if (!expectedDirs.has(entry)) {
      yield* fileSystem
        .remove(nodePath.join(skillsDir, entry), { recursive: true })
        .pipe(Effect.orElseSucceed(() => undefined));
    }
  }
});
